# Import packages

In [2]:
import pandas as pd
import numpy as np
import os

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

from xgboost import XGBClassifier

# Load Data

In [11]:
# Set base path and data path and read event_info and feature_description
base_path = "wind_turbine_fault_detection\Wind_Farm_A"
data_path = os.path.join(base_path, "datasets")
event_info = pd.read_csv(os.path.join(base_path, "event_info.csv"), sep=';')
feature_description = pd.read_csv(os.path.join(base_path, "feature_description.csv"), sep=';')

In [14]:
event_info.head()

,asset,event_id,event_label,event_start,event_start_id,event_end,event_end_id,event_description
0,11,68,anomaly,2023-07-28 13:20:00,52063,2023-08-11 13:10:00,54076,Transformer failure
1,21,22,anomaly,2023-08-12 09:50:00,51888,2023-08-19 10:00:00,52892,Hydraulic group
2,21,72,anomaly,2023-10-10 08:40:00,52497,2023-10-17 08:40:00,53505,Gearbox failure
3,0,73,anomaly,2023-06-10 11:40:00,52745,2023-06-17 11:40:00,53753,Hydraulic group
4,0,0,anomaly,2023-08-06 06:10:00,52436,2023-08-20 06:10:00,54447,Generator bearing failure

In [15]:
feature_description.head()

,sensor_name,statistics_type,description,unit,is_angle,is_counter
0,sensor_0,average,Ambient temperature,�C,False,False
1,sensor_1,average,Wind absolute direction,�,True,False
2,sensor_2,average,Wind relative direction,�,True,False
3,wind_speed_3,"maximum,minimum,average,std_dev",Windspeed,m/s,False,False
4,wind_speed_4,average,Estimated windspeed,m/s,False,False

In [19]:
# Read data
files = ["0.csv","24.csv","26.csv","71.csv","73.csv"]

data_list = []
for f in files:
    df = pd.read_csv(os.path.join(data_path,f), sep=';')
    df["event_id"] = int(f.replace(".csv",""))
    data_list.append(df)

#Show columns
df.columns

Index(['time_stamp', 'asset_id', 'id', 'train_test', 'status_type_id',
       'sensor_0_avg', 'sensor_1_avg', 'sensor_2_avg', 'wind_speed_3_avg',
       'wind_speed_4_avg', 'wind_speed_3_max', 'wind_speed_3_min',
       'wind_speed_3_std', 'sensor_5_avg', 'sensor_5_max', 'sensor_5_min',
       'sensor_5_std', 'sensor_6_avg', 'sensor_7_avg', 'sensor_8_avg',
       'sensor_9_avg', 'sensor_10_avg', 'sensor_11_avg', 'sensor_12_avg',
       'sensor_13_avg', 'sensor_14_avg', 'sensor_15_avg', 'sensor_16_avg',
       'sensor_17_avg', 'sensor_18_avg', 'sensor_18_max', 'sensor_18_min',
       'sensor_18_std', 'sensor_19_avg', 'sensor_20_avg', 'sensor_21_avg',
       'sensor_22_avg', 'sensor_23_avg', 'sensor_24_avg', 'sensor_25_avg',
       'sensor_26_avg', 'reactive_power_27_avg', 'reactive_power_27_max',
       'reactive_power_27_min', 'reactive_power_27_std',
       'reactive_power_28_avg', 'reactive_power_28_max',
       'reactive_power_28_min', 'reactive_power_28_std', 'power_29_avg',
       'power_29_max', 'power_29_min', 'power_29_std', 'power_30_avg',
       'power_30_max', 'power_30_min', 'power_30_std', 'sensor_31_avg',
       'sensor_31_max', 'sensor_31_min', 'sensor_31_std', 'sensor_32_avg',
       'sensor_33_avg', 'sensor_34_avg', 'sensor_35_avg', 'sensor_36_avg',
       'sensor_37_avg', 'sensor_38_avg', 'sensor_39_avg', 'sensor_40_avg',
       'sensor_41_avg', 'sensor_42_avg', 'sensor_43_avg', 'sensor_44',
       'sensor_45', 'sensor_46', 'sensor_47', 'sensor_48', 'sensor_49',
       'sensor_50', 'sensor_51', 'sensor_52_avg', 'sensor_52_max',
       'sensor_52_min', 'sensor_52_std', 'sensor_53_avg', 'event_id'],
      dtype='object')

In [23]:
#Concatenate data
data = pd.concat(data_list)
#Convert to datetime and sort by time_stamp
data["time_stamp"] = pd.to_datetime(data["time_stamp"])
data = data.sort_values("time_stamp")
data = data.reset_index(drop=True)
print(data.shape)
data.head()

(272477, 87)

,time_stamp,asset_id,id,train_test,status_type_id,sensor_0_avg,sensor_1_avg,sensor_2_avg,wind_speed_3_avg,wind_speed_4_avg,...,sensor_48,sensor_49,sensor_50,sensor_51,sensor_52_avg,sensor_52_max,sensor_52_min,sensor_52_std,sensor_53_avg,event_id
0,2022-01-01 00:00:00,0,0,train,0,18.0,178.7,-18.6,4.1,4.4,...,-11991.0,0.0,18831.0,-11991.0,11.1,11.7,10.9,0.1,20.0,71
1,2022-01-01 00:10:00,0,1,train,0,18.0,191.8,-12.2,4.1,4.3,...,-14360.0,0.0,15865.0,-14360.0,11.1,11.3,10.9,0.1,20.0,71
2,2022-01-01 00:20:00,0,2,train,0,18.0,213.8,16.8,4.1,4.4,...,-15524.0,0.0,17244.0,-15524.0,11.1,11.3,10.9,0.1,20.0,71
3,2022-01-01 00:30:00,0,3,train,0,18.0,199.3,-4.6,4.4,4.6,...,-16444.0,0.0,22284.0,-16444.0,11.2,12.4,10.9,0.2,20.0,71
4,2022-01-01 00:40:00,0,4,train,0,18.0,199.9,-4.0,5.5,5.7,...,-16353.0,0.0,49587.0,-16353.0,11.4,12.1,10.9,0.3,20.0,71

# Plot Sensor Timeseries with Event Overlay
- Create a function that, given a sensor name (e.g., `sensor_1_avg`) and a time window, plots the sensor values.
- On the same plot, highlight the periods where `fault_flag == 1` (anomaly events) with a shaded background.
- This is essential for exploratory data analysis.

In [ ]:
def plot_sensor_timeseries(sensor_name,time_wind):
    pass

# EDA

# Define Metrics

# Train an Unsupervised Anomaly Detector

# Alarm Generation with Persistence Filter

# Plot Results